version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - webapp
    volumes:
      - .:/app
networks:
  webapp:
    driver: bridge